### ISSUE TITLE
Premier Personnage

### ISSUE THREAD

**Issue by Daisyqc** [buddyqc69/Quebec_RoseOnlineDev#2]
- [x] #3 
- [x] - Les quetes de Classe non plus ne Fonctionne pas pour apprendre la premiere classe que ca soit muse ,ect... rien de Fonctionne ( urgent ).Hier les personnages de classe était toute la avec les quetes et depuis le crash il y a aucun npc pour choisir ca classe tout a disparu 

![screen008](https://user-images.githubusercontent.com/91747689/135728541-37e52de2-86b2-43cf-b313-9c55555452f9.jpg)

- [ ] #6

**Comment by Daisyqc** [comment]
les citrouilles son de retour

**Comment by buddyqc69** [comment]
> les citrouilles son de retour

Pour le temps de l'halloween ??

**Comment by Daisyqc** [comment]
Non pour la suite de quête qui bug

**Comment by buddyqc69** [comment]
> * [x]  - Les quetes de Classe non plus ne Fonctionne pas pour apprendre la premiere classe que ca soit muse ,ect... rien de Fonctionne ( urgent ).Hier les personnages de classe était toute la avec les quetes et depuis le crash il y a aucun npc pour choisir ca classe tout a disparu
> 
> ![screen008](https://user-images.githubusercontent.com/91747689/135728541-37e52de2-86b2-43cf-b313-9c55555452f9.jpg)

Le problème devrait être résolu
